# Generated by Django 5.0.4 on 2024-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0002_remove_todo_date_remove_todo_time_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
