# Generated by Django 5.0.4 on 2024-05-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0003_alter_todo_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
