# Generated by Django 5.0.4 on 2024-05-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0005_completedtodo_alter_todo_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('due_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('risk', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20)),
                ('effort', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CompletedTodo',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
