# Generated by Django 5.0.4 on 2024-05-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoList', '0006_task_delete_completedtodo_delete_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
        migrations.AddField(
            model_name='task',
            name='duration_unit',
            field=models.CharField(default='Minutes', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='duration_value',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='effort',
            field=models.TextField(blank=True, null=True),
        ),
    ]
